//Nav Bar Information:
const details = [
  {
    title: "Blog Section",
    classHome: "home-links",
    classBlog: "home-links active",
    classDesign: "home-links",
    classPort: "home-links",
    classEssay: "home-links",
  },
  {
    title: "Design Section",
    classHome: "home-links",
    classBlog: "home-links",
    classDesign: "home-links active",
    classPort: "home-links",
    classEssay: "home-links",
  },
  {
    title: "Portfolio Section",
    classHome: "home-links",
    classBlog: "home-links",
    classDesign: "home-links",
    classPort: "home-links active",
    classEssay: "home-links",
  },
  {
    title: "Essay Section",
    classHome: "home-links",
    classBlog: "home-links",
    classDesign: "home-links",
    classPort: "home-links",
    classEssay: "home-links active",
  },
  {
    title: "Blog Posts",
    classHome: "home-links",
    classBlog: "home-links",
    classDesign: "home-links",
    classPort: "home-links",
    classEssay: "home-links ",
  },
];

//Blog Posts Information:
const blogInfo = [
  {
    id: 0,
    icon: "powerIcon.png",
    link: "blog-post1.html",
    heading: "WEEK #01 - INTRODUCTION TO INTERACTIVE MEDIA",
    desc: "I discuss a few readings and touch on my experience with GitHub.",
    date: "FEBRUARY 27, 2023",
    dataCode: "week-1",
  },
  {
    id: 1,
    icon: "htmlIcon.png",
    link: "blog-post2.html",
    heading: "WEEK #02 - HTML FUNDAMENTALS",
    desc: "My first interaction with HTML as a programming language.",
    date: "MARCH 6, 2023",
    dataCode: "week-2",
  },
  {
    id: 2,
    icon: "cssIcon.png",
    link: "blog-post3.html",
    heading: "WEEK #03 - WEBSITE PROGRESS & CSS FUNDAMENTALS",
    desc: "My first interaction with HTML as a programming language.",
    date: "MARCH 10, 2023",
    dataCode: "week-3",
  },
  {
    id: 3,
    icon: "jsIcon.png",
    link: "blog-post4.html",
    heading: "WEEK #04 - USER INTERFACE AND JAVASCRIPT",
    desc: "I dive a little deeper into UI and I also reflect on my experience with JavaScript.",
    date: "MARCH 20, 2023",
    dataCode: "week-4",
  },
  {
    id: 4,
    icon: "tickIcon.png",
    link: "blog-post5.html",
    heading: "WEEK #05 & #06 BLOGS & REFLECTION",
    desc: "My final analysis before submission",
    date: "April 15, 2023",
    dataCode: "week-5",
  },
  {
    id: 5,
    icon: "light-bulb.png",
    link: "blog-post6.html",
    heading: "WEEK #07 - FINAL THOUGHTS ON MY WEBSITE",
    desc: "I discuss my website and some of the concepts that I have worked with throughout my progress.",
    date: "April 7, 2023",
    dataCode: "week-7",
  },

  {
    id: 7,
    icon: "reading.png",
    link: "blog-post8.html",
    heading: "WEEK #09 - Writing a close reading",
    desc: "This was a challenging task for me as I often ramble on when writing but, I now see the importance of active reading.",
    date: "April 28, 2023",
    dataCode: "week-9",
  },
  {
    id: 8,
    icon: "tech.png",
    link: "blog-post9.html",
    heading: "WEEK #10 - Technocolonialism",
    desc: "I discuss technocolonialism as a whole.",
    date: "May 5, 2023",
    dataCode: "week-10",
  },
  {
    id: 9,
    icon: "timer-new.png",
    link: "blog-post10.html",
    heading: "WEEK #11 - Website Progress",
    desc: "I fell behind during this week and the blog post was based more on my website reading.",
    date: "May 12, 2023",
    dataCode: "week-10",
  },
  {
    id: 10,
    icon: "earth.png",
    link: "blog-post11.html",
    heading:
      "WEEK #12 - Reflecting on the lack of inclusivity in our daily lives",
    desc: "I reflect on the reading and discuss how I believe inclusivity can be achieved.",
    date: "May 19, 2023",
    dataCode: "week-10",
  },
];

const homeData = [
  {
    title: "Blog Section",
    link: "blog.html",
    img: "./2438840_KeenanKistoo_FinalWebsite/icons/blog.png",
    desc: "Discussions, reflections and thoughts during my first semester of Interactive Media III in 2023.",
  },
  {
    title: "Design Section",
    link: "design.html",
    img: "./2438840_KeenanKistoo_FinalWebsite/icons/design.png",
    desc: "My thought process when designing this website.",
  },
  {
    title: "Portfolio",
    link: "portfolio.html",
    img: "./2438840_KeenanKistoo_FinalWebsite/icons/profile.png",
    desc: "A bit of information about myself and also the work that I am particularly proud of.",
  },
  {
    title: "Essay Section",
    link: "essay.html",
    img: "./2438840_KeenanKistoo_FinalWebsite/icons/essay.png",
    desc: "The essays that I have completed during this semester.",
  },
];
